package kr.wise.csr.importfile;

public enum WorkbookType {
    WISEDQ_RESULT,
    WDQ_CRITERIA,
    CRITERIA_VERIFICATION_RULE,
    CRITERIA_REFERENCE_INTEGRITY,
    CRITERIA_DOMAIN_MAPPING,
    CRITERIA_BUSINESS_RULE,
    CRITERIA_EXCLUSION_PATTERN,
    CRITERIA_TABLE_EXCLUSION,
    CRITERIA_COLUMN_EXCLUSION,
    CRITERIA_CODE_RULE
}
